const $=s=>document.querySelector(s);const app=$('#app');
const LOCATION_IMAGES={hall:'assets/locations/hall.png',library:'assets/locations/library.png',kitchen:'assets/locations/kitchen.png',garden:'assets/locations/garden.png',study:'assets/locations/study.png',secret:'assets/locations/secret.png'};
const CHARACTER_PORTRAITS={lord:'assets/characters/lord_greywood.png',henry:'assets/characters/henry.png',emily:'assets/characters/emily.png',maria:'assets/characters/maria.png',tom:'assets/characters/tom.png',elsa:'assets/characters/elsa.png',doctor:'assets/characters/doctor.png'};
const CHARACTERS={
 lord:{name:'Лорд Грейвуд',role:'хозяин поместья',bio:'Влиятельный владелец Грейвуд-Холла. Перед смертью собирался признать Эльзу и изменить порядок наследования.'},
 henry:{name:'Генри',role:'наследник под подозрением',bio:'Формальный наследник с серьёзными долгами. Кажется опасным, но пытается решить вопрос через адвоката, а не через убийство.'},
 emily:{name:'Эмили',role:'библиотекарь',bio:'Внимательная, собранная и осторожная. Лучше других замечает мелочи и движения по дому ночью.'},
 maria:{name:'Мария',role:'кухарка',bio:'Старая служанка дома, суровая и практичная. Слишком болезненно воспринимает всё, что может разрушить привычный порядок.'},
 tom:{name:'Том',role:'садовник',bio:'Немногословный смотритель зимнего сада. Видел больше, чем хотел бы, и боится потерять работу из-за правды.'},
 elsa:{name:'Эльза',role:'внебрачная дочь лорда',bio:'Молодая женщина, чьё появление меняет всё дело. Сама не знала всей правды о завещании до самого утра.'},
 doctor:{name:'Доктор Уитмор',role:'семейный врач',bio:'Сдержанный и наблюдательный доктор. Именно он первым понял, что смерть лорда была слишком тихой и подозрительно быстрой.'}
};
const TALK_SCENES={
 doctor:{character:'doctor',name:'Доктор Уитмор',headline:'Разговор с доктором',text:'Доктор говорит негромко и без лишней театральности: «Смерть наступила быстро. Борьбы не было. Для меня это выглядит не как приступ, а как действие вещества, которое ударило по сердцу почти сразу». Он подчёркивает: время смерти — около полуночи.'},
 emily:{character:'emily',name:'Эмили',headline:'Разговор с Эмили',text:'Эмили долго молчит, а потом признаётся: «Я видела Марию с подносом. Она сказала, что лорд просил чай поздно ночью. Мне это показалось странным, но я не стала вмешиваться». Её голос тихий, но она уверена в увиденном.'},
 maria:{character:'maria',name:'Мария',headline:'Разговор с Марией',text:'Мария отвечает сухо и сдержанно. Чем подробнее вопросы о чае и завещании, тем заметнее её раздражение: «Я делала свою работу. А кто что там писал в бумагах — не моё дело». Она путается во времени и избегает прямого взгляда.'},
 tom:{character:'tom',name:'Том',headline:'Разговор с Томом',text:'Том мнётся, опускает глаза и наконец говорит: «После полуночи я видел Марию у оранжереи. Она срезала что-то с клумбы и велела мне забыть об этом. Я промолчал — боялся, что меня выгонят».'},
 henryTalk:{character:'henry',name:'Генри',headline:'Разговор с Генри',text:'Генри раздражён, но говорит прямо: «Да, я в долгах. Но если бы я хотел всё исправить силой, я бы не отправлял телеграмму адвокату в ту же ночь. Я рассчитывал оспорить завещание законно, а не убивать собственного дядю». В его словах слишком много злости, но они звучат логично.'},
 elsaTalk:{character:'elsa',name:'Эльза',headline:'Разговор с Эльзой',text:'Эльза говорит тихо и растерянно: «Я приехала только утром. О признании и новом завещании я ничего не знала. Если бы он позвал меня раньше, возможно, всё сложилось бы иначе». Кажется, её больше ранит сама правда о семье, чем наследство.'}
};
const DATA={
locations:{hall:{name:'Парадный холл',mood:'Запах мокрого сукна, воск и холодный сквозняк из галереи.',desc:'В центре холла лежит тело лорда Грейвуда. На ковре нет следов борьбы, но серебряный поднос с чашкой стоит слишком аккуратно, будто его вернули на место уже после смерти.',actions:[['Осмотреть чашку','cup'],['Проверить камин','ash'],['Поговорить с доктором','doctor'],['Поговорить с Генри','henryTalk'],['Перейти в библиотеку','go:library'],['Перейти на кухню','go:kitchen']]},library:{name:'Библиотека',mood:'Дубовые полки уходят в темноту, а лестница на рельсе тихо качается, хотя никто её не трогал.',desc:'Здесь лорд хранил письма, старые долговые расписки и последнюю версию завещания. На столе виден прямоугольник чистой пыли: отсюда недавно забрали папку.',actions:[['Изучить стол','desk'],['Окно в сад','window'],['Расспросить Эмили','emily'],['Искать тайную нишу','niche'],['Вернуться в холл','go:hall'],['В сад','go:garden']]},kitchen:{name:'Кухня',mood:'Медь кастрюль отражает тусклые лампы, на плите ещё тёплый чайник.',desc:'Кухня — место, где можно незаметно приготовить напиток. Но люди здесь привыкли замечать каждую мелочь.',actions:[['Осмотреть чайник','kettle'],['Проверить кладовую','store'],['Поговорить с Марией','maria'],['Вернуться в холл','go:hall']]},garden:{name:'Зимний сад',mood:'За стеклом шумит дождь. Влажная земля хранит следы лучше любого свидетеля.',desc:'Дорожка ведёт к оранжерее и сараю садовника. На клумбе не хватает нескольких стеблей наперстянки — растения красивого, но опасного.',actions:[['Следы у окна','prints'],['Клумба наперстянки','foxglove'],['Поговорить с Томом','tom'],['Сарай','shed'],['В библиотеку','go:library']]},study:{name:'Кабинет лорда',mood:'Комната заперта изнутри на показ, но замок слишком новый для старой двери.',desc:'В кабинете нет хаоса. Здесь не искали вслепую — отсюда забрали только один документ и оставили всё остальное как театральную декорацию.',actions:[['Папка завещания','will'],['Сейф','safe'],['Письмо Эльзе','elsaLetter'],['Поговорить с Эльзой','elsaTalk'],['Тайная комната','go:secret'],['В холл','go:hall']]},secret:{name:'Тайная архивная',mood:'Узкая комната за книжной полкой. Воздух сухой, как в склепе.',desc:'Внутри лежат документы о внебрачной дочери лорда и список выплат. Правда оказывается не громкой, а бухгалтерски точной.',actions:[['Досье Эльзы','elsa'],['Последняя записка','lastNote'],['Вернуться в кабинет','go:study']]}}
};
let S={loc:'hall',time:18,acts:0,e:{},notes:[],unlocked:{hall:1,library:1,kitchen:1,garden:1},trust:{emily:50,tom:50,maria:50},log:[]};
const facts={cup:['Яд был в чае','На ободке чашки горький травяной след. Это не лекарство Генри: запах совпадает с наперстянкой из сада.'],ash:['Сожжённое письмо','В камине обрывок: «…если завещание уйдёт девочке, дом погибнет».'],doctor:['Тихая смерть около полуночи','Доктор подтверждает: борьбы не было, смерть наступила быстро, вероятно от сердечного яда.'],henryTalk:['Генри пытался действовать законно','Генри признаёт долги, но утверждает, что хотел оспорить завещание через адвоката. Это ослабляет версию о том, что он решился на убийство.'],desk:['Папка завещания исчезла','На столе чистый прямоугольник пыли. Папку забрали недавно и знали точное место.'],window:['Путь через окно','Грязь на подоконнике совпадает с землёй зимнего сада.'],emily:['Эмили видела ночной чай','Библиотекарь признаётся: около полуночи Мария несла чай в холл, но сказала, что это просьба лорда.'],niche:['Найден рычаг кабинета','За каталогом спрятан латунный рычаг. Открыт доступ в кабинет.',()=>S.unlocked.study=1],kettle:['Чайник кипятили ночью','На плите свежая накипь, кухня работала после отбоя.'],store:['Пропали сушёные травы','Из кладовой исчез маленький пакет с сушёной наперстянкой.'],maria:['Мария лжёт о времени','Мария путает время и злится, когда речь заходит о завещании. Она боялась сокращения кухни.'],prints:['Маленькие следы к библиотеке','Следы идут от оранжереи к окну библиотеки. Размер не совпадает с Генри и Джеймсом.'],foxglove:['Срезанная наперстянка','Стебли срезаны аккуратно кухонным ножом, не садовыми ножницами.'],tom:['Том видел Марию в саду','Садовник видел Марию у оранжереи после полуночи, но молчал из страха потерять место.'],shed:['Флакон настоя','В сарае найден флакон с остатками настоя наперстянки.',()=>S.e.vial=1],will:['Последнее завещание','Лорд оставлял имение Эльзе, внебрачной дочери. Старые слуги теряли власть и деньги.'],safe:['Долги Генри не главная причина','Генри разорён, но в ночь смерти он отправил телеграмму адвокату, пытаясь оспорить завещание законно.'],elsaLetter:['Эльза должна была приехать утром','Лорд собирался признать Эльзу публично на следующий день.'],elsa:['Эльза не убийца','Её документы были спрятаны от неё самой. Она не знала о финальном завещании до утра.'],elsaTalk:['Эльза ничего не знала о наследстве','Эльза уверяет, что приехала лишь утром и не знала о решении лорда. Её показания совпадают с письмом из кабинета.'],lastNote:['Последняя записка лорда','«Мария считает, что я предал дом. Надо поговорить с ней при свидетелях».']};
function add(k){if(S.e[k])return;let f=facts[k];S.e[k]={title:f[0],text:f[1]};S.log.unshift(f[0]);if(f[2])f[2]();S.acts++;S.time+=.25;save();render();}
function save(){localStorage.greywoodPremium=JSON.stringify(S)}function load(){try{S=JSON.parse(localStorage.greywoodPremium)||S}catch{}}function reset(){localStorage.removeItem('greywoodPremium');location.reload()}
function go(id){if(!S.unlocked[id])return modal('Закрыто','Нужна улика, которая объясняет доступ к этой локации.');S.loc=id;S.acts++;save();render()}
function action(v){if(TALK_SCENES[v])return talkToCharacter(v);if(v.startsWith('go:'))return go(v.slice(3));add(v)}
function evidence(){return Object.entries(S.e).map(([k,v])=>`<div class="ev"><b>${v.title}</b><br>${v.text}</div>`).join('')||'<p class="tag">Улик пока нет. Осматривайте локации и сверяйте показания.</p>'}
function characterPortrait(key){return `<div class="characterMedia"><img src="${CHARACTER_PORTRAITS[key]}" alt="${CHARACTERS[key]?.name||key}" class="characterPortrait"></div>`}
function talkToCharacter(key){let info=TALK_SCENES[key];if(!info)return;add(key);let ev=S.e[key];let portraitKey=info.character||key;modal(info.headline,`<div class="characterDialog">${characterPortrait(portraitKey)}<div class="characterCopy"><div class="characterRole">${info.name}</div><p class="ending">${info.text}</p><div class="ev talkEvidence"><b>${ev.title}</b><br>${ev.text}</div></div></div>`)}
function characterGallery(){return Object.entries(CHARACTERS).map(([key,char])=>`<div class="characterCard">${characterPortrait(key)}<div class="characterBody"><h3>${char.name}</h3><div class="characterRole">${char.role}</div><p>${char.bio}</p></div></div>`).join('')}
function render(){let L=DATA.locations[S.loc];let sceneImage=LOCATION_IMAGES[S.loc]||'';app.innerHTML=`<div class="shell"><aside class="hero"><p class="kicker">interactive detective</p><h1 class="brand">Грейвуд:<br>Последний протокол</h1><p class="tag">Премиальная сюжетная веб-игра: ищите улики, проверяйте алиби, открывайте локации и выносите обвинение только когда цепочка доказательств сходится.</p><div class="stats"><div class="stat"><b>Время</b>${Math.floor(S.time)}:${S.time%1?'15':'00'}</div><div class="stat"><b>Действий сделано</b>${S.acts}</div><div class="stat"><b>Открыто локаций</b>${Object.keys(S.unlocked).length}/6</div></div><button class="btn primary" onclick="verdict()">Вынести вердикт</button> <button class="btn danger" onclick="reset()">Новая игра</button></aside><main class="main"><div class="top"><span class="pill">Текущая сцена</span><span class="pill">${L.name}</span></div><section class="scene"><div class="art">${sceneImage?`<div class="sceneImage" style="background-image:url('${sceneImage}')"></div>`:''}<div class="sceneText"><div class="kicker">${L.mood}</div><h2 class="title">${L.name}</h2><p class="desc">${L.desc}</p></div></div><div class="content"><div class="card"><h3>Действия</h3><div class="choices">${L.actions.map(a=>`<button class="btn choice" onclick="action('${a[1]}')">${a[0]}<small>${a[1].startsWith('go:')?'перемещение':'осмотр / диалог / улика'}</small></button>`).join('')}</div></div><div class="card"><h3>Досье улик</h3><div class="evidence">${evidence()}</div></div></div></section><section class="dock"><button class="btn" onclick="modal('Журнал', '${S.log.map(x=>'• '+x).join('<br>')||'Пока пусто'}')">Журнал</button><button class="btn" onclick="modal('Персонажи', '<div class=\"characterGrid\">'+characterGallery()+'</div>')">Персонажи</button><button class="btn" onclick="modal('Подсказка','Ищите связку: способ убийства → доступ к яду → ночное действие → мотив из завещания. Ложный след Генри ломается через сейф и телеграмму.')">Подсказка</button><button class="btn" onclick="modal('Промпты для будущих изображений', prompts())">Промпты сцен</button><button class="btn" onclick="exportSave()">Экспорт</button><button class="btn" onclick="importSave()">Импорт</button></section></main></div>`}
function modal(t,c){let m=document.createElement('div');m.className='modal';m.innerHTML=`<div class="modalBox"><h2 class="title">${t}</h2><div class="ending">${c}</div><br><button class="btn primary" onclick="this.closest('.modal').remove()">Закрыть</button></div>`;document.body.appendChild(m)}
function verdict(){modal('Финальный вердикт',`<label>Кто убийца?</label><select id="killer"><option>Генри</option><option>Эмили</option><option>Мария</option><option>Том</option></select><label>Орудие</label><select id="weapon"><option>Пистолет</option><option>Нож</option><option>Яд в чае</option></select><label>Мотив</label><select id="motive"><option>Наследство Эльзы и потеря положения</option><option>Ревность</option><option>Случайная драка</option></select><button class="btn primary" onclick="checkVerdict()">Проверить обвинение</button>`)}
function checkVerdict(){let ok=$('#killer').value=='Мария'&&$('#weapon').value=='Яд в чае'&&$('#motive').value.includes('Эльзы');let need=['cup','doctor','kettle','foxglove','tom','will','lastNote'];let solid=need.every(k=>S.e[k]);modal(ok&&solid?'Дело раскрыто':'Вердикт преждевременен',ok&&solid?'<p class="ok">Мария убила лорда настоем наперстянки в ночном чае. Мотив — завещание в пользу Эльзы: признание дочери разрушало старый порядок дома и лишало Марию будущего влияния.</p><p>Цепочка доказательств сходится: яд, чайник, растение, свидетель Том, завещание и последняя записка.</p>':'<p class="bad">Обвинение не держится. Нужна полная цепочка доказательств, а не отдельные подозрения.</p>')}
function prompts(){let L=DATA.locations[S.loc];return `<p><b>${L.name}</b></p><p>Cinematic premium detective game scene, 1890s English manor, ${L.name}, ${L.mood} ${L.desc}, moody warm lamp light, rain outside, realistic materials, elegant composition, no text, 16:9.</p>`}
function exportSave(){navigator.clipboard?.writeText(JSON.stringify(S));modal('Экспорт','Сохранение скопировано в буфер обмена.')}function importSave(){let v=prompt('Вставьте JSON сохранения');if(v){S=JSON.parse(v);save();render()}}
load();render();
